apiVersion: v1
kind: Secret
metadata:
  name: todoapp-secret
  namespace: todoapp
type: Opaque
stringData:
  DB_HOST: "dummy"
  DB_PORT: "5432"
  DB_NAME: "dummy"
  DB_USER: "dummy"
  DB_PASSWORD: "dummy"
  DB_SSL: "false"