FROM nginx:1.27-alpine

COPY app/frontend/index.html /usr/share/nginx/html/index.html
COPY app/frontend/styles.css /usr/share/nginx/html/styles.css
COPY app/frontend/src /usr/share/nginx/html/src
COPY app/frontend/nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80