services:
  backend:
    container_name: todoapp-backend
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    env_file:
      - .env
    environment:
      PORT: ${PORT}
      STORAGE_DRIVER: ${STORAGE_DRIVER}
      TASKS_FILE: ${TASKS_FILE}
    volumes:
      - ../db:/usr/src/db
    restart: unless-stopped
    networks:
      - todoapp-network

  frontend:
    container_name: todoapp-frontend
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:80"
    restart: unless-stopped
    networks:
      - todoapp-network

networks:
  todoapp-network:
    name: todoapp-network