apiVersion: v1
kind: Service
metadata:
  name: todoapp-backend-service
  namespace: todoapp
spec:
  type: ClusterIP
  selector:
    app: todoapp-backend
  ports:
    - port: 5000
      targetPort: 5000