name: todoapp-ci-cd

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image tag
        id: vars
        run: echo "TAG=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Build backend image
        run: |
          docker build -t todoapp-backend:${{ steps.vars.outputs.TAG }} -f docker/Dockerfile.backend .

      - name: Build frontend image
        run: |
          docker build -t todoapp-frontend:${{ steps.vars.outputs.TAG }} -f docker/Dockerfile.frontend .

      - name: Tag backend image
        run: |
          docker tag todoapp-backend:${{ steps.vars.outputs.TAG }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/todoapp-prod-backend:${{ steps.vars.outputs.TAG }}

      - name: Tag frontend image
        run: |
          docker tag todoapp-frontend:${{ steps.vars.outputs.TAG }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/todoapp-prod-frontend:${{ steps.vars.outputs.TAG }}

      - name: Push backend image
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/todoapp-prod-backend:${{ steps.vars.outputs.TAG }}

      - name: Push frontend image
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/todoapp-prod-frontend:${{ steps.vars.outputs.TAG }}